name: furigana
description: Automatic furigana annotation and rendering for Japanese text.
version: 0.1.0
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mecab_dart: ^0.1.6
  collection: ^1.18.0
  ruby_text: ^3.0.3

flutter:
  assets:
    - assets/ipadic/